export const JOB_QUEUE_TOKEN = Symbol('JOB_QUEUE');
export const JOB_QUEUE_CONNECTION_TOKEN = Symbol('JOB_QUEUE_CONNECTION');
export const JOB_WORKER_CONNECTION_TOKEN = Symbol('JOB_WORKER_CONNECTION');
